# Generated by Django 5.2.6 on 2025-09-21 16:44

import apps.audiobook.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recognition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('page_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('full_text', models.TextField(help_text='The complete processed text content')),
                ('confidence', models.FloatField(help_text='Confidence score for the text processing (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('processing_time', models.FloatField(help_text='Time taken to process the text in seconds', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('language', models.CharField(default='en', help_text="Language code (e.g., 'en' for English)", max_length=10)),
                ('results', models.JSONField(blank=True, help_text='Raw OCR results in JSON format', null=True)),
            ],
            options={
                'db_table': 'audiobook_page_recognitions',
            },
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('audio_file', models.FileField(upload_to=apps.audiobook.models.audio_file_path)),
                ('file_format', models.CharField(max_length=10)),
                ('bitrate', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField()),
                ('file_size_bytes', models.BigIntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audiobook_audio_files',
                'ordering': ['recognition', 'created_at'],
            },
        ),
    ]
