# Generated by Django 5.2.6 on 2025-09-24 17:53

import apps.audiobook.models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('task_id', models.CharField(help_text='Unique ID for the OCR processing task', max_length=100, null=True, unique=True)),
                ('page_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('audio_file', models.FileField(help_text='Generated audio file for the page', max_length=500, storage=apps.audiobook.models.AudioFileStorage, upload_to=apps.audiobook.models.audio_file_path)),
                ('file_format', models.CharField(max_length=10)),
                ('bitrate', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField()),
                ('file_size_bytes', models.BigIntegerField()),
                ('result', models.JSONField(blank=True, help_text='Raw TTS results in JSON format', null=True)),
            ],
            options={
                'db_table': 'audiobook_audio_files',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('task_id', models.CharField(help_text='Unique ID for the OCR processing task', max_length=100, null=True, unique=True)),
                ('page_file', models.FileField(help_text='Uploaded image file of the page', max_length=500, storage=apps.audiobook.models.PageFileStorage, upload_to=apps.audiobook.models.page_file_path)),
                ('file_format', models.CharField(max_length=10)),
                ('page_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('full_text', models.TextField(help_text='The complete processed text content')),
                ('language', models.CharField(default='en', help_text="Language code (e.g., 'en' for English)", max_length=10)),
                ('result', models.JSONField(blank=True, help_text='Raw OCR results in JSON format', null=True)),
            ],
            options={
                'db_table': 'audiobook_page_files',
            },
        ),
    ]
