# Generated by Django 5.2.6 on 2025-09-21 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audiobook', '0001_initial'),
        ('library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recognition',
            name='biblio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_recognitions', to='library.biblio'),
        ),
        migrations.AddField(
            model_name='recognition',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recognition',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='recognition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='audiobook.recognition'),
        ),
        migrations.AddIndex(
            model_name='recognition',
            index=models.Index(fields=['biblio'], name='audiobook_p_biblio__6897dd_idx'),
        ),
        migrations.AddIndex(
            model_name='recognition',
            index=models.Index(fields=['page_number'], name='audiobook_p_page_nu_8a0310_idx'),
        ),
        migrations.AddIndex(
            model_name='recognition',
            index=models.Index(fields=['created_by', 'biblio'], name='audiobook_p_created_5e9244_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recognition',
            unique_together={('biblio', 'page_number')},
        ),
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['recognition'], name='audiobook_a_recogni_00aded_idx'),
        ),
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['created_by'], name='audiobook_a_created_37a84e_idx'),
        ),
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['file_format'], name='audiobook_a_file_fo_b9fd7d_idx'),
        ),
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['duration_seconds'], name='audiobook_a_duratio_5bae40_idx'),
        ),
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['file_size_bytes'], name='audiobook_a_file_si_5a13ab_idx'),
        ),
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['created_at'], name='audiobook_a_created_a296f1_idx'),
        ),
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['recognition', 'created_at'], name='audiobook_a_recogni_462dc7_idx'),
        ),
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['created_by', 'recognition'], name='audiobook_a_created_409189_idx'),
        ),
    ]
