# Generated by Django 5.2.6 on 2025-09-22 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audiobook', '0001_initial'),
        ('library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='biblio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='library.biblio'),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagefile',
            name='biblio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_files', to='library.biblio'),
        ),
        migrations.AddField(
            model_name='pagefile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagefile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['biblio'], name='audiobook_a_biblio__474be0_idx'),
        ),
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['created_by'], name='audiobook_a_created_37a84e_idx'),
        ),
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['file_format'], name='audiobook_a_file_fo_b9fd7d_idx'),
        ),
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['duration_seconds'], name='audiobook_a_duratio_5bae40_idx'),
        ),
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['file_size_bytes'], name='audiobook_a_file_si_5a13ab_idx'),
        ),
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['created_at'], name='audiobook_a_created_a296f1_idx'),
        ),
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['biblio', 'created_at'], name='audiobook_a_biblio__65dd43_idx'),
        ),
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['created_by', 'biblio'], name='audiobook_a_created_a914a6_idx'),
        ),
        migrations.AddIndex(
            model_name='pagefile',
            index=models.Index(fields=['biblio'], name='audiobook_p_biblio__46e4dc_idx'),
        ),
        migrations.AddIndex(
            model_name='pagefile',
            index=models.Index(fields=['page_number'], name='audiobook_p_page_nu_424656_idx'),
        ),
        migrations.AddIndex(
            model_name='pagefile',
            index=models.Index(fields=['created_by', 'biblio'], name='audiobook_p_created_0ddac5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pagefile',
            unique_together={('biblio', 'page_number')},
        ),
    ]
