# Generated by Django 5.2.6 on 2025-09-24 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audiobook', '0001_initial'),
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='biblio_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='tracker.bibliocollection'),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagefile',
            name='biblio_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_files', to='tracker.bibliocollection'),
        ),
        migrations.AddField(
            model_name='pagefile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagefile',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['biblio_collection'], name='audiobook_a_biblio__a424f7_idx'),
        ),
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['created_by'], name='audiobook_a_created_37a84e_idx'),
        ),
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['file_format'], name='audiobook_a_file_fo_b9fd7d_idx'),
        ),
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['duration_seconds'], name='audiobook_a_duratio_5bae40_idx'),
        ),
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['file_size_bytes'], name='audiobook_a_file_si_5a13ab_idx'),
        ),
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['created_at'], name='audiobook_a_created_a296f1_idx'),
        ),
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['biblio_collection', 'created_at'], name='audiobook_a_biblio__011c65_idx'),
        ),
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['created_by', 'biblio_collection'], name='audiobook_a_created_ac8869_idx'),
        ),
        migrations.AddIndex(
            model_name='pagefile',
            index=models.Index(fields=['biblio_collection'], name='audiobook_p_biblio__bd88a5_idx'),
        ),
        migrations.AddIndex(
            model_name='pagefile',
            index=models.Index(fields=['page_number'], name='audiobook_p_page_nu_424656_idx'),
        ),
        migrations.AddIndex(
            model_name='pagefile',
            index=models.Index(fields=['created_by', 'biblio_collection'], name='audiobook_p_created_0ae3e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pagefile',
            unique_together={('biblio_collection', 'page_number')},
        ),
    ]
