# Generated by Django 5.2.6 on 2025-09-22 16:33

import apps.audiobook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobook', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='audio_file',
            field=models.FileField(help_text='Generated audio file for the page', max_length=500, storage=apps.audiobook.models.AudioFileStorage, upload_to=apps.audiobook.models.audio_file_path),
        ),
        migrations.AlterField(
            model_name='pagefile',
            name='page_file',
            field=models.FileField(help_text='Uploaded image file of the page', max_length=500, storage=apps.audiobook.models.PageFileStorage, upload_to=apps.audiobook.models.page_file_path),
        ),
    ]
