# Generated by Django 5.2.6 on 2025-09-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobook', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='language',
            field=models.CharField(default='en', help_text="Language code (e.g., 'en' for English)", max_length=10),
        ),
    ]
