# Generated by Django 5.2.6 on 2025-09-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobook', '0003_alter_audiofile_audio_file_alter_pagefile_page_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagefile',
            name='file_format',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
