# Generated by Django 5.2.6 on 2025-09-25 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobook', '0003_audiofile_language'),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audiofiles', to='audiobook.pagefile'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='biblio_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiofiles', to='tracker.bibliocollection'),
        ),
    ]
