# Generated by Django 5.2.6 on 2025-09-23 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobook', '0004_pagefile_file_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiofile',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='pagefile',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RemoveField(
            model_name='audiofile',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='pagefile',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='audiofile',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagefile',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
    ]
