# Generated by Django 5.2.6 on 2025-09-26 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobook', '0004_audiofile_page_alter_audiofile_biblio_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='page',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audiofile', to='audiobook.pagefile'),
        ),
    ]
