# Generated by Django 5.2.6 on 2025-09-26 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiobook', '0005_alter_audiofile_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiofile',
            old_name='page',
            new_name='page_file',
        ),
    ]
