# Generated by Django 5.2.6 on 2025-09-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobook', '0007_pagefile_voice_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='voice_gender',
            field=models.CharField(default='male', help_text="Voice gender for TTS (e.g., 'male', 'female')", max_length=10),
        ),
    ]
