# Generated by Django 5.2.6 on 2025-09-23 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='bibliocollection',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='bibliomark',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='readinggoal',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='readingprogress',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='readingsession',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RemoveField(
            model_name='bibliocollection',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='bibliomark',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='readinggoal',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='readingprogress',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='readingsession',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='bibliocollection',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bibliomark',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collection',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='readinggoal',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='readingsession',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
    ]
