# Generated by Django 5.2.6 on 2025-09-24 00:52

import django.contrib.postgres.search
import django.core.validators
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0004_alter_biblio_genres_alter_biblio_publishers_and_more'),
        ('tracker', '0002_rename_updated_at_bibliocollection_modified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliocollection',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bibliocollection',
            name='edition_number',
            field=models.CharField(blank=True, help_text="e.g., '2nd Edition', 'Revised'", max_length=50),
        ),
        migrations.AddField(
            model_name='bibliocollection',
            name='edition_title',
            field=models.CharField(blank=True, help_text='Edition-specific title if different', max_length=500),
        ),
        migrations.AddField(
            model_name='bibliocollection',
            name='edition_type',
            field=models.CharField(choices=[('first', 'First Edition'), ('revised', 'Revised Edition'), ('reprint', 'Reprint'), ('anniversary', 'Anniversary Edition'), ('special', 'Special Edition'), ('international', 'International Edition'), ('translation', 'Translation'), ('abridged', 'Abridged Edition'), ('unabridged', 'Unabridged Edition'), ('illustrated', 'Illustrated Edition'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='bibliocollection',
            name='file_format',
            field=models.CharField(blank=True, choices=[('PDF', 'PDF'), ('EPUB', 'EPUB'), ('MOBI', 'MOBI'), ('TXT', 'Text'), ('HTML', 'HTML'), ('AUDIOBOOK', 'Audiobook'), ('HARDCOVER', 'Hardcover'), ('PAPERBACK', 'Paperback')], max_length=20),
        ),
        migrations.AddField(
            model_name='bibliocollection',
            name='file_path',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='bibliocollection',
            name='file_size_mb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bibliocollection',
            name='genres',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='library.TaggedGenre', to='library.Genre', verbose_name='Genres'),
        ),
        migrations.AddField(
            model_name='bibliocollection',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bibliocollection',
            name='issn',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bibliocollection',
            name='language',
            field=models.CharField(default='en', help_text='Original language', max_length=10),
        ),
        migrations.AddField(
            model_name='bibliocollection',
            name='original_publication_date',
            field=models.DateField(blank=True, help_text='First publication date of the work', null=True),
        ),
        migrations.AddField(
            model_name='bibliocollection',
            name='original_title',
            field=models.CharField(blank=True, help_text='Original title if translated', max_length=500),
        ),
        migrations.AddField(
            model_name='bibliocollection',
            name='publishers',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='library.TaggedPublisher', to='library.Publisher', verbose_name='Publishers'),
        ),
        migrations.AddField(
            model_name='bibliocollection',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='bibliocollection',
            name='title',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bibliocollection',
            name='total_pages',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
