# Generated by Django 5.2.6 on 2025-09-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_bibliocollection_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliocollection',
            name='publication_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year of publication', null=True),
        ),
    ]
