# Generated by Django 5.2.6 on 2025-09-24 06:57

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0006_taggedauthor_biblio_authors'),
        ('tracker', '0004_bibliocollection_publication_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliocollection',
            name='authors',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='library.TaggedAuthor', to='library.Author', verbose_name='Authors'),
        ),
    ]
